name: CI/CD Tesis - Laravel Postgres & React
on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: TEST BACKEND (Con Base de Datos PostgreSQL) ---
  test-backend:
    runs-on: ubuntu-latest
    
    # Esto crea una base de datos PostgreSQL "fantasma" solo para el test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        # Esperamos a que la DB esté lista antes de seguir
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./Proyecto1

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pgsql, pdo_pgsql # Necesario para Postgres
    
    - name: Instalar Dependencias
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generar Key
      run: |
        cp .env.example .env
        php artisan key:generate
        
    - name: Ejecutar Tests
      #
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: test_db
        DB_USERNAME: test_user
        DB_PASSWORD: 123456
      run: |
        php artisan migrate --force # Crea las tablas en la DB de prueba
        php artisan test            # Corre los tests

  # --- JOB 2: BUILD FRONTEND ---
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./miapp-web
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Build
      run: |
        npm install
        npm run build

  # --- JOB 3: DEPLOY  ---
  deploy:
    needs: [test-backend, build-frontend]
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      
      - name: Desplegar Backend
        run: |
          # Sincronizar archivos (ajusta las rutas de destino)
          rsync -av --exclude='.git' ./backend/ /var/www/html/tesis-backend/
          
          # Comandos post-deploy
          cd /var/www/html/tesis-backend/
          composer install --optimize-autoloader --no-dev
          
          # IMPORTANTE: Asegúrate de que el .env DE TU SERVIDOR (el real) tenga la IP de tu Docker real
          php artisan migrate --force
          php artisan optimize

      - name: Desplegar Frontend
        run: |
          cd ./frontend
          npm install && npm run build
          rsync -av ./dist/ /var/www/html/tesis-frontend/
